### ISSUE TITLE
Version is not updated when version parameter changes

### ISSUE THREAD

**Issue by bregell** [voxpupuli/puppet-vault#29]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: 3.0.0

## How to reproduce (e.g Puppet code you use)
Set $vault::install_method = 'archive'
Set $vault::version to e.g. '1.13.1'

## What are you seeing
The output of the command 'vault --version' is the old version i.e. 1.2.2

## What behaviour did you expect instead
I expect the module to update the executable i.e. output of the command 'vault --version' should be 1.13.1

**Comment by C24-AK** [comment]
Still an issue, any workarounds?
